apiVersion: 1

datasources:
  - name: Local Prometheus
    uid: local-prometheus
    type: prometheus
    access: proxy
    url: http://172.30.0.1:19091
    isDefault: true
    editable: false
    jsonData:
      timeInterval: 30s
